Site=https://demoqa.com/
MainMenu=//div[@id='app']/header/a
Interactions=//h5[contains(text(),'Interactions')]
Droppable=//span[starts-with(text(),'Droppable')]
Simple_DragMe=//div[text()='Drag me']
Simple_DropHere=//div[@id='simpleDropContainer']//p
Simple_Dropped=//div[@id='simpleDropContainer']//p
Accept=//a[(text()='Accept')]
Acceptable=//div[@id='acceptable']
NotAcceptable=//div[@id='notAcceptable']
Accept_DropHere=//div[@id='acceptDropContainer']//p
Accept_Dropped=//div[@id='acceptDropContainer']//p
Forms=//h5[text()='Forms']
PracticeForms=//span[text()='Practice Form']
FormName=//input[@id='firstName']
FormLastName=//input[@id='lastName']
FormEmail=//input[@id='userEmail']
FormGender=//label[text()='Male']
FormMobileNumber=//input[@id='userNumber']
FormDateofBirth=NA
FormSubjects=NA
FormHobbies=//input[@id='hobbies-checkbox-1']//parent::div
FormPicture=NA
FormCurrntAddress=//textarea[@id='currentAddress']
FormState=//div[@id='state']/div
FormCity=//div[@id='city']/div
FormSubMitBtn=//button[text()='Submit']
FormDOBText=//td[text()='Date of Birth']
FormClose=//button[@id='closeLargeModal']
FormData=Not in Ue brp
