Site=https://demoqa.com/
MainMenu=//div[@id='app']/header/a
Interactions=//h5[contains(text(),'Interactions')]
Droppable=//span[starts-with(text(),'Droppable')]
Simple_DragMe=//div[text()='Drag me']
Simple_DropHere=//div[@id='simpleDropContainer']//p
Simple_Dropped=//div[@id='simpleDropContainer']//p
Accept=//a[(text()='Accept')]
Acceptable=//div[@id='acceptable']
NotAcceptable=//div[@id='notAcceptable']
Accept_DropHere=//div[@id='acceptDropContainer']//p
Accept_Dropped=//div[@id='acceptDropContainer']//p
